server {
    listen 80;
    server_name #{SUB_DOMAIN}#.#{DOMAIN}#;
    add_header X-Content-Type-Options nosniff;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self'; font-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self';" always;

location / {
    root /data/www;
    index index.html;
}
}